name: $(Date:yyyyMM).$(Rev:r)-$(SourceBranchName)

trigger:
  branches:
    include:
    - master
    - hotfix/*
    - feature/*  

pool:
  vmImage: 'ubuntu-latest'

variables:
  shortBuildName: $[replace(variables['Build.BuildNumber'], '-master', '')]
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    tags: -t humanprinter.azurecr.io/ser2net:latest -t humanprinter.azurecr.io/ser2net:$(shortBuildName)
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    tags: -t humanprinter.azurecr.io/ser2net:$(Build.BuildNumber)

steps:
- task: Docker@2
  displayName: Docker Login
  inputs:
    containerRegistry: 'acr_humanprinter'
    command: 'login'
- task: CmdLine@2
  displayName: Build
  inputs:
    script: |
      docker run --privileged --rm tonistiigi/binfmt --install arm64,arm
      docker run --privileged --rm tonistiigi/binfmt
      docker buildx create --use
      docker buildx build --platform linux/arm64,linux/arm/v7,linux/arm/v6 \
        $(tags) \
        --push \
        ./src/
